services:
  
  server:
    # build:
    #   context: ./server
    image: faizms14/my-social-media-app-server:v1.0
    env_file: .env
    container_name: my-social-media-app-server
    environment:
    - REDIS_URL=redis://redis:6379
    networks:
      - proxy_net
      - my-social-media-app-net
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_net
      traefik.http.routers.my-social-media-app-api.rule: Host(`api-mysosmed.faizms.com`)
      traefik.http.routers.my-social-media-app-api.entrypoints: websecure
      traefik.http.routers.my-social-media-app-api.tls.certresolver: myresolver
      traefik.http.services.my-social-media-app-api.loadbalancer.server.port: 80
  
  database:
    image: mongo:latest
    container_name: my-social-media-app-db
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my-social-media-app-user
      - MONGO_INITDB_ROOT_PASSWORD=my-social-media-app-password888
      - MONGO_INITDB_DATABASE=my-social-media-app-db
    volumes:
      - my-social-media-app-db-volume:/data/db
    networks:
      - my-social-media-app-net
  
  redis:
    image: redis:latest
    container_name: my-social-media-app-redis
    # ports:
    #   - 6379:6379
    networks:
      - my-social-media-app-net

networks:
  my-social-media-app-net:
    driver: bridge
  proxy_net:
    external: true

volumes:
  my-social-media-app-db-volume: